version: "3.2"
services:
  firestore_emulator:
    image: mtlynch/firestore-emulator
    environment:
      - FIRESTORE_PROJECT_ID=restaurant-app-review-ststem
    ports:
      - 8200:8200
  app:
    image: your-app-image
    environment:
      - FIRESTORE_EMULATOR_HOST=firestore_emulator:8200
      - FIRESTORE_PROJECT_ID=restaurant-app-review-ststem
  depends_on:
    - firestore_emulator